version: '3.8'


networks:
  frontend-tier:
    driver: bridge


services:
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./build/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/nginx/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./app/public:/home/app/web/files/public:ro
      - ./app/dist:/home/app/web/files/dist:ro

    ports:
      - ${NGINX_PORT}:80
    networks:
      - frontend-tier
